### ISSUE TITLE
Some Entries cannot be deleted

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#113]
Sometimes, when uploading a new image to a Entry or deleting an entry, we receive errors like these:
```console
FirebaseError: Missing or insufficient permissions.
```

```console
"TypeError: Cannot read properties of null (reading '_throwIfRoot') 
  at uploadBytes$1 (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/firebase_storage.js?v=19af0a4b:1905:8)
  at uploadBytes (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/firebase_storage.js?v=19af0a4b:2163:10)
  at Proxy.uploadImage (http://localhost:9200/src/stores/entries.js:130:13)
  at Proxy.<anonymous> (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/pinia.js?v=19af0a4b:1057:22)
  at store.<computed> (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/pinia.js?v=19af0a4b:754:34)
  at Proxy.onSubmit (http://localhost:9200/src/components/EntryCard.vue:79:16)
  at http://localhost:9200/src/components/EntryCard.vue:145:82 at http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/chunk-OHD66QDB.js?v=19af0a4b:8535:12
  at callWithErrorHandling (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/chunk-OHD66QDB.js?v=19af0a4b:1378:18)
  at callWithAsyncErrorHandling (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/chunk-OHD66QDB.js?v=19af0a4b:1386:17)
  at emit$1 (http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/chunk-OHD66QDB.js?v=19af0a4b:1818:5)
  at http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/chunk-OHD66QDB.js?v=19af0a4b:6934:45
  at http://localhost:9200/node_modules/.q-cache/vite/pwa/deps/quasar_dist_quasar_esm_js.js?v=19af0a4b:14753:13"
```

```console
"FirebaseError: Firebase Storage:
  User does not have permission to access 'images/entry-2022-12T1676389962463'. (storage/unauthorized)"
```

**Comment by arnonrdp** [comment]
Solved the errors above, now getting this one:
```console
Uncaught (in promise) Error: FirebaseError:
Firebase Storage: Object 'images/entry-2022-02T1676434702864' does not exist. (storage/object-not-found)
    at errors.js?t=1677093975028:26:17
    at <anonymous>
    at async Proxy.throwError (errors.js?t=1677093975028:19:7)
```
