### ISSUE TITLE
[BUG] Email sign up doesn't work sometimes

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#271]
Authentication error:

```console
index.90a3e85e.js:21 FirebaseError: Firebase: Error (auth/operation-not-allowed).
    at Qa (firebase.d53734a9.js:2386:587)
    at Ce (firebase.d53734a9.js:2386:30)
    at Ef (firebase.d53734a9.js:2491:1213)
    at async Cr (firebase.d53734a9.js:2491:1350)
    at async sA (firebase.d53734a9.js:3046:759)
    at async Proxy.emailSignUp (index.90a3e85e.js:21:112)
    at async o (ProfilePage.c9e4d33e.js:1:1743)
```

**Comment by arnonrdp** [comment]
Fixed directly in the Firebase console.

@stravid87

**Comment by stravid87** [comment]
@arnonrdp   
Closer.... I am now able to log in -- well done. However,

1) On log out, I can't log back in.
2) On commenting, I am represented as an anonymous user.

**Comment by arnonrdp** [comment]
> 1. On log out, I can't log back in.

This one is fixed.

> 2. On commenting, I am represented as an anonymous user.

I created a new issue to resolve this: #278.
